Param()

$ErrorActionPreference = "Stop"

$allowedName = "wlrjs1300-coder"
$allowedEmail = "wlrjs1300@gmail.com"
$forbiddenMessagePatterns = @(
  "co-authored-by",
  "signed-off-by",
  "generated by",
  "chatgpt",
  "claude",
  "codex",
  "ai-generated"
)

function Test-AllowedIdentity([string]$name, [string]$email) {
  return ($name -eq $allowedName -and $email -eq $allowedEmail)
}

function Test-CommitMessage([string]$message) {
  foreach ($pattern in $forbiddenMessagePatterns) {
    if ($message -match "(?i)$([regex]::Escape($pattern))") {
      Write-Host "[FORBIDDEN] Commit message contains prohibited text: $pattern" -ForegroundColor Red
      return $false
    }
  }
  return $true
}

function Fail([string]$message) {
  Write-Host "[FORBIDDEN] $message" -ForegroundColor Red
  exit 1
}

function Check-Commit([string]$sha) {
  $raw = git show -s --format='%H|%an|%ae|%cn|%ce|%B' $sha
  if ([string]::IsNullOrWhiteSpace($raw)) {
    return
  }

  $parts = $raw -split "\|", 6
  $authorName = $parts[1]
  $authorEmail = $parts[2]
  $committerName = $parts[3]
  $committerEmail = $parts[4]
  $message = $parts[5]

  if (-not (Test-AllowedIdentity $authorName $authorEmail)) {
    Fail "Commit $sha author '$authorName <$authorEmail>' is not allowed."
  }

  if (-not (Test-AllowedIdentity $committerName $committerEmail)) {
    Fail "Commit $sha committer '$committerName <$committerEmail>' is not allowed."
  }

  if (-not (Test-CommitMessage $message)) {
    Fail "Commit $sha message is not allowed."
  }
}

if ($env:GITHUB_ACTIONS -eq "true") {
  if (-not (Test-Path $env:GITHUB_EVENT_PATH)) {
    Write-Host "[SKIP] GitHub Actions context not fully available for commit inspection." -ForegroundColor Yellow
    exit 0
  }

  $payload = Get-Content -Raw $env:GITHUB_EVENT_PATH | ConvertFrom-Json
  $eventName = $env:GITHUB_EVENT_NAME
  $range = $null

  if ($eventName -eq "pull_request") {
    $baseSha = $payload.pull_request.base.sha
    $headSha = $payload.pull_request.head.sha
    $range = "$baseSha..$headSha"
  } elseif ($eventName -eq "push") {
    $before = $payload.before
    $after = $payload.after
    if ($before -and $after) {
      $range = "$before..$after"
    }
  }

  if ([string]::IsNullOrWhiteSpace($range)) {
    Write-Host "[SKIP] Commit range is not available; nothing to check in this event." -ForegroundColor Yellow
    exit 0
  }

  $commits = git rev-list --no-merges --reverse $range
  if ([string]::IsNullOrWhiteSpace($commits)) {
    Write-Host "[OK] No non-merge commit found to check."
    exit 0
  }

  Write-Host "[CHECK] Verifying author/committer and commit messages in range: $range"
  foreach ($sha in ($commits -split "`n")) {
    if ([string]::IsNullOrWhiteSpace($sha)) { continue }
    Check-Commit $sha
  }
  Write-Host "[OK] Git author policy check passed for CI commit range."
  exit 0
}

try {
  $name = git config user.name
  $email = git config user.email
} catch {
  Write-Host "[SKIP] git is not available in current context." -ForegroundColor Yellow
  exit 0
}

if ([string]::IsNullOrWhiteSpace($name) -or [string]::IsNullOrWhiteSpace($email)) {
  Fail "git user.name/user.email is not configured."
}

if (-not (Test-AllowedIdentity $name $email)) {
  Fail "local git config '$name <$email>' is not allowed."
}

Write-Host "[OK] git author is configured to allowed identity."
Write-Host "name : $name"
Write-Host "email: $email"
