Param(
  [string]$RootPath = (Get-Location).Path
)

$ErrorActionPreference = "Stop"
Set-Location $RootPath

$WarningSize = 5MB
$FailSize = 10MB

$warningCount = 0
$errorCount = 0

$forbiddenPaths = @(".claude", ".codex", ".agents", ".cursor", "prompt-history", "session-logs", "agent-logs", "scratchpad")
$forbiddenFiles = @(".env", ".env.local", ".env.development", ".env.production", ".env.test", "CLAUDE.md", "AGENTS.md", "AI_NOTES.md", "AI_LOG.md")
$forbiddenExtPatterns = @("*.pem", "*.key", "*.p12", "*.pfx", "*.sql", "*.dump", "*.bak", "*.db", "*.sqlite", "*.sqlite3")
$forbiddenStrings = @(
  "co-authored-by",
  "signed-off-by",
  "generated by chatgpt",
  "generated by claude",
  "generated by codex",
  "generated with ai",
  "assisted by ai"
)
$forbiddenStringExcludeFiles = @(
  ".github/PULL_REQUEST_TEMPLATE.md",
  "scripts/README.md",
  "04-development-git-rules.md",
  "scripts/check-git-author.ps1",
  "scripts/check-repo-policy.ps1"
)
$secretExcludeFiles = @(
  ".github/PULL_REQUEST_TEMPLATE.md",
  "scripts/README.md",
  "04-development-git-rules.md",
  "scripts/check-repo-policy.ps1"
)

$secretPatterns = @(
  @{ Name = "private-key-header"; Pattern = "-----BEGIN [A-Z ]*PRIVATE KEY-----" },
  @{ Name = "token-like"; Pattern = '(?i)\b(?:api[_-]?key|secret|token|password|private[_-]?key)\s*[:=]\s*["'']?[^"\r\n ]{16,}["'']?' },
  @{ Name = "api-provider-like"; Pattern = '(?i)\b(?:openai|github|aws|google|azure|stripe|supabase|clerk|slack)\s+(?:api[_-]?key|token|secret)\s*[:=]\s*["'']?[^"\r\n ]{16,}["'']?' },
  @{ Name = "generic-secret-like"; Pattern = '(?i)\b(?:key|secret)\s*[:=]\s*["'']?[A-Za-z0-9\-_]{24,}["'']?' }
)
$allowedPlaceholders = "(?i)(replace-with-|example|placeholder|dummy|test-only|<[^>]+>)"
$scanExcludeDirs = @(".git", "node_modules", ".next", ".venv", "dist", "coverage")

function Add-Warning([string]$message) {
  Write-Host "[WARN]  $message" -ForegroundColor Yellow
  $script:warningCount++
}

function Add-Error([string]$message) {
  Write-Host "[ERROR] $message" -ForegroundColor Red
  $script:errorCount++
}

function ToRelative([string]$fullPath) {
  $root = (Get-Location).ProviderPath.TrimEnd('\') + "\"
  if ($fullPath.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)) {
    return $fullPath.Substring($root.Length).Replace("\", "/")
  }
  return $fullPath.Replace("\", "/")
}

function IsUnder([string]$path, [string[]]$names) {
  $normalized = $path -replace "[\\/]", "/"
  foreach ($name in $names) {
    if ($normalized -match "(^|/)$([regex]::Escape($name))(/|$)") {
      return $true
    }
  }
  return $false
}

function IsExcludedPath([string]$fullPath) {
  $normalized = $fullPath -replace "[\\/]", "/"
  foreach ($name in $scanExcludeDirs) {
    if ($normalized -match "(^|/)$([regex]::Escape($name))(/|$)") {
      return $true
    }
  }
  return $false
}

function IsRepository() {
  try {
    git rev-parse --is-inside-work-tree > $null 2>&1
    return $true
  } catch {
    return $false
  }
}

function Get-TrackedAndStaged() {
  $tracked = git ls-files
  $staged = git diff --cached --name-only
  $all = @()
  if ($tracked) { $all += $tracked }
  if ($staged) { $all += $staged }
  return ($all | Sort-Object -Unique)
}

function ContainsForbiddenString([string]$path, [string]$content) {
  $normalizedPath = $path -replace "\\", "/"
  if ($forbiddenStringExcludeFiles -contains $normalizedPath) {
    return $null
  }
  foreach ($needle in $forbiddenStrings) {
    if ($content -match "(?i)$needle") {
      return $needle
    }
  }
  return $null
}

function DetectSecret([string]$path, [string]$content) {
  $normalizedPath = $path -replace "\\", "/"
  if ($secretExcludeFiles -contains $normalizedPath) {
    return $null
  }
  foreach ($entry in $secretPatterns) {
    if ($content -match $entry.Pattern) {
      $match = $Matches[0]
      if ($match -match $allowedPlaceholders) {
        continue
      }
      return $entry.Name
    }
  }
  return $null
}

Write-Host "Repository policy check (v0.1.0 foundation) start."

$isRepo = IsRepository
$candidateFiles = @()
$trackedOrStaged = @()

if ($isRepo) {
  $trackedOrStaged = Get-TrackedAndStaged
  $candidateFiles = @($trackedOrStaged)
} else {
  Write-Host "Git 저장소가 아직 초기화되지 않아 Git 추적 상태 검사는 생략했습니다."
  Write-Host "파일 시스템 기준 정책 검사는 실행했습니다."
  $candidateFiles = Get-ChildItem -Recurse -File -Force |
    Where-Object { -not (IsExcludedPath $_.FullName) } |
    ForEach-Object { ToRelative $_.FullName }
}

if ($isRepo) {
  $forbiddenPathFiles = $candidateFiles | Where-Object { IsUnder $_ $forbiddenPaths }
  if ($forbiddenPathFiles.Count -gt 0) {
    Add-Error "Tracked/staged files in forbidden paths: $($forbiddenPathFiles -join ', ')"
  }
}

foreach ($relativePath in $candidateFiles) {
  $leaf = Split-Path $relativePath -Leaf
  $fullPath = Join-Path (Get-Location) $relativePath

  if ($forbiddenFiles -contains $leaf) {
    Add-Error "Forbidden file name: $relativePath"
  }

  if ($forbiddenExtPatterns | Where-Object { $leaf -like $_ }) {
    Add-Error "Forbidden file extension: $relativePath"
  }

  try {
    $fileInfo = Get-Item -LiteralPath $fullPath -ErrorAction Stop
    if ($fileInfo.Length -gt $FailSize) {
      Add-Error "File exceeds 10MB: $relativePath ($([math]::Round($fileInfo.Length / 1MB, 2)) MB)"
    } elseif ($fileInfo.Length -gt $WarningSize) {
      Add-Warning "File exceeds 5MB: $relativePath ($([math]::Round($fileInfo.Length / 1MB, 2)) MB)"
    }
  } catch {
    continue
  }

  $content = $null
  try {
    $content = Get-Content -Raw -LiteralPath $fullPath -ErrorAction Stop
  } catch {
    continue
  }

  $forbiddenHit = ContainsForbiddenString $relativePath $content
  if ($forbiddenHit) {
    Add-Error "Forbidden string ('$forbiddenHit') in $relativePath"
  }

  $secretHit = DetectSecret $relativePath $content
  if ($secretHit) {
    Add-Error "Secret-like pattern ('$secretHit') in $relativePath"
  }
}

if ($isRepo) {
  if ($trackedOrStaged -contains ".env") {
    Add-Error "Tracked/staged forbidden file: .env"
  }
}

if ($errorCount -gt 0) {
  Write-Host "Policy check failed. Errors: $errorCount, Warnings: $warningCount" -ForegroundColor Red
  exit 1
}

if ($warningCount -gt 0) {
  Write-Host "Policy check passed with warnings. Warnings: $warningCount" -ForegroundColor Yellow
  exit 0
}

Write-Host "Policy check passed." -ForegroundColor Green
